prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

SELECT * {
  {
    SELECT DISTINCT ?item {
      ?item a lrcommon:BS7666Address .
    }
  }
  
  ?item ?p ?o .
  
  SERVICE <http://landregistry.data.gov.uk/landregistry/query> {
    FILTER NOT EXISTS {
      ?item ?p ?o .
    }
  }

}