#!/bin/bash

set -e

# figure out what directory the script is in
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPTS_DIR/image-config
source $SCRIPTS_DIR/image-lib

for VOCAB in $VOCAB_DIR/*
do
  convertTtl $VOCAB
done