#!/bin/bash

set -e

# figure out what directory the script is in
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPTS_DIR/image-config

if [ ! -e $NQUADS_DIR/PPD.nq.gz ]
then
  echo converting PPD data
  java -Xmx1024M -jar $PPD_CONVERTER_JAR --publishDate 2015-10-29 --input $CSV_DIR/appd-test.csv | gzip > $NQUADS_DIR/PPD.nq.gz
fi
